branches:
  only:
    - master
language: node_js
node_js:
  - 16
#cache:
#  directories:
#   - node_modules
install:
  - yarn install
script:
  - yarn compile
  - npm adduser
  - npm run patch-release
deploy:
  - provider: npm
    email: $email
    api_key: $npm_token
    skip_cleanup: true
    on:
      branch: master