branches:
  only:
    - master
language: node_js
node_js:
  - 16
#cache:
#  directories:
#   - node_modules
install:
  - yarn install
script:
  - yarn compile
  - npm run prepare-release
deploy:
#  - provider: npm
#    email: $email
#    api_key: $npm_token
#    skip_cleanup: true
#    on:
#      branch: master
#  - provider: releases
#    api_key: $github_token
#    skip_cleanup: true
#    on:
#      branch: master
after_deploy:
  - .travis/push.sh